version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

dependencies:
  python: requirements.txt
  galaxy: requirements.yml

additional_build_files:
  - src: files/
    dest: tmp/files/

options:
  package_manager_path: /usr/bin/microdnf
