version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs'

dependencies:
  python:
    - requests
    - netaddr>=0.10.1

  galaxy:
    collections:
      - name: amazon.aws
      - name: ansible.netcommon
      - name: ansible.network
      - name: ansible.posix
      - name: ansible.security
      - name: ansible.utils
      - name: fortigate.fortios
      - name: arista.eos
      - name: cisco.asa
      - name: cisco.ios
      - name: cisco.iosxr
      - name: cisco.nxos

options:
  package_manager_path: /usr/bin/microdnf
