---
collections:
  - name: amazon.aws
  - name: ansible.netcommon
  - name: ansible.windows
  - name: ansible.network
  - name: ansible.posix
  - name: ansible.security
  - name: ansible.utils
  - name: fortigate.fortios
  - name: arista.eos
  - name: cisco.asa
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.nxos
